# Generated by Django 5.2.6 on 2025-09-09 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_price_p', models.PositiveIntegerField()),
                ('vat_rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('covers', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal_p', models.PositiveIntegerField(default=0)),
                ('service_charge_p', models.PositiveIntegerField(default=0)),
                ('vat_total_p', models.PositiveIntegerField(default=0)),
                ('total_p', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TabItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('unit_price_p', models.PositiveIntegerField()),
                ('vat_rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat_p', models.PositiveIntegerField()),
                ('line_total_p', models.PositiveIntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabs.menuitem')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tabs.tab')),
            ],
        ),
    ]
