# Generated by Django 5.2.6 on 2025-09-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
