# Generated by Django 5.2.6 on 2025-09-09 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tabs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(max_length=100, unique=True)),
                ('amount_p', models.PositiveIntegerField()),
                ('currency', models.CharField(default='gbp', max_length=3)),
                ('status', models.CharField(choices=[('requires_confirmation', 'Requires Confirmation'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=50)),
                ('failure_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tabs.tab')),
            ],
        ),
    ]
